AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate deployment of Docker Hub image with auto-created VPC and security group

Parameters:
  DockerHubUsername:
    Type: String
    Description: Docker Hub username
  DockerHubImage:
    Type: String
    Description: Docker Hub image name
  ContainerPort:
    Type: Number
    Default: 80
    Description: Port exposed by the container

Resources:
  ### VPC ###
  FastApiVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: fastapi-vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref FastApiVPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref FastApiVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref FastApiVPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  ### Security Group ###
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP access
      VpcId: !Ref FastApiVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          CidrIp: 0.0.0.0/0

  ### ECS Cluster ###
  FastApiCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: fastapi-cluster

  ### ECS Task Execution Role ###
  FastApiTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  ### ECS Task Definition ###
  FastApiTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: fastapi-task
      RequiresCompatibilities: [FARGATE]
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt FastApiTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: fastapi
          Image: !Sub "${DockerHubUsername}/${DockerHubImage}:latest"
          PortMappings:
            - ContainerPort: !Ref ContainerPort

  ### ECS Service ###
  FastApiService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref FastApiCluster
      TaskDefinition: !Ref FastApiTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PublicSubnet
          SecurityGroups:
            - !Ref ECSSecurityGroup

Outputs:
  ECSCluster:
    Value: !Ref FastApiCluster
    Description: ECS Cluster Name
  ECSService:
    Value: !Ref FastApiService
    Description: ECS Service Name